services:
  - type: web
    name: db_gacho_store
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    envVars:
      - key: DATABASE_URL
        value: "your-database-url"
    routes:
      - type: http
        name: "http"
        path: "/"
