services:
  - type: web
    name: db_gacho_store
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    envVars:
      - key: DATABASE_URL
        value: "https://api.render.com/deploy/srv-csmojm0gph6c73fngl70?key=qS1Mm3XgC8E"
    routes:
      - type: http
        name: "http"
        path: "/"
